; A table of books and thier authers.
(setf BOOKS '((WAR-AND-PEACE LEO-TOLSTOY)
	      (THE-LORD-OF-THE-RINGS J-R-R-TOLKIEN)
	      (THE-HITCHHIKERS-GUIDE-TO-THE-GALAXY DOUGLAS-ADAMS)
	      (ALICE-IN-WONDERLAND LEWIS CARROLL)
	      (HARRY-POTTER J-K-ROWLING)))
